import discord
from discord import app_commands
from discord.ext import commands

class Records(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @app_commands.command(name="recordsauthor", description="Show the records created by a specific user.")
    @app_commands.default_permissions(view_audit_log=True)
    async def recordsauthor(self, interaction: discord.Interaction, user: discord.User):
        await interaction.response.send_message(f"### Records generated by: **{user.name}** (ID: {user.id})\nSearching logs...")

        try:
            found_logs = False
            async for entry in interaction.guild.audit_logs(limit=10, user=user): 
                found_logs = True
                log_message = (
                    f"**Moderator:** <@{entry.user_id}>\n"
                    f"**Action:** {entry.action}\n"
                    f"**Target:** {entry.target}\n"
                    f"**Reason:** {entry.reason if entry.reason else 'No reason provided'}\n"
                    "---"
                )
                await interaction.followup.send(content=log_message)

            if not found_logs:
                await interaction.followup.send("No recent audit log entries found for this user.", ephemeral=True)

        except discord.Forbidden:
            await interaction.followup.send("I do not have 'View Audit Log' permissions.", ephemeral=True)
        except Exception as e:
            print(f"Error checking logs: {e}")
            await interaction.followup.send("An error occurred while fetching logs.", ephemeral=True)

    @app_commands.command(name="recordstarget", description="Show records targeted at a user.")
    @app_commands.default_permissions(view_audit_log=True)
    async def recordstarget(self, interaction: discord.Interaction, user: discord.User):
        await interaction.response.send_message(f"### Actions targeted at: **{user.name}**\nSearching...")
        try:
            results = []
            async for entry in interaction.guild.audit_logs(limit=100):
                if entry.target and entry.target.id == user.id:
                    results.append(
                        f"**Target:** {entry.target}\n"
                        f"**Action:** {entry.action}\n"
                        f"**Moderator:** <@{entry.user_id}>\n"
                        f"**Reason:** {entry.reason or 'No reason provided'}\n"
                        "---"
                    )

            if not results:
                await interaction.followup.send("No records targeting this user found within the last 100 entries.", ephemeral=True)
            else:
                full_log = "\n".join(results)
                await interaction.followup.send(content=full_log[:2000], ephemeral=True)

        except discord.Forbidden:
            await interaction.followup.send("I do not have 'View Audit Log' permissions.", ephemeral=True)
        except Exception as e:
            print(f"Error checking targets: {e}")
            await interaction.followup.send("An error occurred.", ephemeral=True)

async def setup(bot: commands.Bot):
    await bot.add_cog(Records(bot))